all:
	pandoc -V documentclass=report -V colorlinks=true -V linkcolor=red -V urlcolor=blue --from=markdown+multiline_tables game-authors-guide.md -o ../game-authors-guide.pdf
	pandoc -V documentclass=article -V colorlinks=true -V linkcolor=red -V urlcolor=blue --from=markdown+multiline_tables getting-started.md -o ../getting-started.pdf
