all:
	pandoc -V documentclass=report --from=markdown+multiline_tables game-authors-guide.md -o ../game-authors-guide.pdf
	pandoc -V documentclass=article --from=markdown+multiline_tables getting-started.md -o ../getting-started.pdf
